### ISSUE TITLE
[BUG] User stories don't load in Mozilla Firefox, in self hosted version

### ISSUE THREAD

**Issue by TudorAndrei** [taigaio/taiga-front#169] opened 2022-10-14 14:15 UTC
This issue was also found in ![the original taiga repo](https://github.com/taigaio/taiga-front/issues/2256)

**Describe the bug**

User stories don't load. Please see attached image

**How can we reproduce the behavior**

Run a self hosted version of taiga and create a user story.
**Workarounds**

Use a chromium browser. I tried with Brave and it worked.
**Screenshots**

![image](https://user-images.githubusercontent.com/25133006/195868003-0ecb7d28-8e39-46bf-accd-da09c4f2a1aa.png)
**Taiga environment**

Network tab:

GEThttps://ops.pythia.social/api/v1/userstories/by_ref?order_by=kanban_order&project=2&status=8
[HTTP/1.1 400 Bad Request 26ms]

XHRGEThttps://ops.pythia.social/api/v1/userstories/by_ref?order_by=kanban_order&project=2&status=8
[HTTP/1.1 400 Bad Request 26ms]

	
GET
	https://ops.pythia.social/api/v1/userstories/by_ref?order_by=kanban_order&project=2&status=8
Status
400
Bad Request
VersionHTTP/1.1
Transferred1.02 kB (21 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    Access-Control-Allow-Credentials
    	true
    Access-Control-Allow-Headers
    	content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id,set-orders
    Access-Control-Allow-Methods
    	GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD
    Access-Control-Allow-Origin
    	*
    Access-Control-Expose-Headers
    	x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones,taiga-info-backlog-total-userstories,taiga-info-userstories-without-swimlane,taiga-info-project-memberships,taiga-info-project-is-private,taiga-info-order-updated
    Access-Control-Max-Age
    	1800
    Allow
    	GET, HEAD, OPTIONS
    Connection
    	keep-alive
    Content-Language
    	en
    Content-Length
    	21
    Content-Type
    	application/json
    Date
    	Fri, 14 Oct 2022 14:13:18 GMT
    Server
    	nginx/1.18.0 (Ubuntu)
    Vary
    	Accept-Language
    X-Frame-Options
    	SAMEORIGIN
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en
    Authorization
    	Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1ODM4NDU3LCJqdGkiOiJmMmIzZWI4MzA0MDM0N2FkODRlMGIyZWZlZWEwMzM4YiIsInVzZXJfaWQiOjZ9.D5_y_MlugfSpt_SFQQRi0hQuWvmYcol8PA84VMSesAQ
    Connection
    	keep-alive
    Cookie
    	TS01c70f9d=017c5c4d468f220317640e8dabdd32f41f945311e82c10eadb47dc3bbd5031da8a7b331e8da5d803ee9d44d2292b6a2f0dc31e88dc
    DNT
    	1
    Host
    	ops.pythia.social
    Referer
    	https://ops.pythia.social/project/test/us/2?kanban-status=8
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
    x-disable-pagination
    	1
    X-Session-Id
    	8b2066aee54f558129e1fd661f424c339ce64c42

This is the request header

```
GET /api/v1/userstories/by_ref?order_by=kanban_order&project=2&status=8 HTTP/1.1
Host: ops.pythia.social
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Accept: application/json, text/plain, */*
Accept-Language: en
Accept-Encoding: gzip, deflate, br
x-disable-pagination: 1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY1ODM4NDU3LCJqdGkiOiJmMmIzZWI4MzA0MDM0N2FkODRlMGIyZWZlZWEwMzM4YiIsInVzZXJfaWQiOjZ9.D5_y_MlugfSpt_SFQQRi0hQuWvmYcol8PA84VMSesAQ
X-Session-Id: 8b2066aee54f558129e1fd661f424c339ce64c42
Referer: https://ops.pythia.social/project/test/us/2?kanban-status=8
DNT: 1
Connection: keep-alive
Cookie: TS01c70f9d=017c5c4d468f220317640e8dabdd32f41f945311e82c10eadb47dc3bbd5031da8a7b331e8da5d803ee9d44d2292b6a2f0dc31e88dc
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```

Self hosted. In dev console I get the follwing 

**Desktop (please complete the following information):**
 - **OS:** Linux
 - **Browser:** Firefox  
 - **Version:** 106.0

**Comment by Xaviju** [comment] 2022-10-28 08:49
Hi, @TudorAndrei 
I am not able to reproduce this error in my end.
Is there any error in the devtools console? 
Could you test if it works in taiga.io?
Could you try with the same browser in incognito mode?

**Comment by Xaviju** [comment] 2022-10-31 11:30
A user reported the same error and the issue was external

> i found a reason! The ClearURLs addon blocked something. After disabling taiga works fine!

Please, could you test it in a private window or another browser?

**Comment by Xaviju** [comment] 2022-10-31 11:43
Closing this for now, please reopen if the error persist

**Closed as completed by Xaviju** 2022-10-31 11:43 UTC
Labels: bug

**Comment by TudorAndrei** [comment] 2022-11-03 09:54
Yes, that was my issue too. Thank you!
