### ISSUE TITLE
custom font icons not shown

### ISSUE THREAD

**Issue by drzraf** [taigaio/taiga-front#975] opened 2016-04-24 15:19 UTC
I use firefox 38 (Debian) and realized that the user-story page missed icon (trash-icon & co) over the color (I discovered that the day I wanted to delete task without finding where to click)
It happens that firefox may have issue loading with some relative path.

From the (Persistent) "Font" tab of the "Network" tab of firebug I see:
```
https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Regular.ttf
https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Light.ttf
https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Semibold.ttf
https://tree.taiga.io/v-1461242229586/fonts/OpenSans-CondLight.ttf

```
In the console I can see:

```
downloadable font: kern: Too large subtable., table discarded (font-family: "OpenSans-Regular" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Regular.ttf
downloadable font: kern: Too large subtable., table discarded (font-family: "OpenSans-Light" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Light.ttf
downloadable font: kern: Too large subtable., table discarded (font-family: "OpenSans-Semibold" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1461242229586/fonts/OpenSans-Semibold.ttf
```

==> https://bugzilla.mozilla.org/show_bug.cgi?id=1185685

When I do redact IRL SCRUM-stories/tasks, my pen does not download 4 fonts 800 kB worth (note that after the hard-refresh, the whole page takes like 1 minute to load...)

**Comment by Xaviju** [comment] 2016-04-24 17:32
What version of Taiga are you using? Self-hosted version or taiga.io? Taiga is not using font icons anymore, it is using SVG sprites so this problem should not be related.
The font you are indicating is the Open sans font and the error seems not related to this problem.

**Comment by drzraf** [comment] 2016-04-24 21:27
The issue exists on taiga.io.
You're probably right about OpenSans since this police does not seems to include symbols.
These are two distinct issues then.
But I've no warning and waiting minute or more taiga.io loading (this sooo bitbucket) is painful (it's even longer with firebug).
I'll post here if I can grab more clues.
In the meantime, feel free to try to reproduce it.

**Comment by drzraf** [comment] 2016-04-24 21:43
You're right. I can see SVG markup in the source. Don't know why it does not show up.

**Comment by Xaviju** [comment] 2016-04-25 05:30
Please attach a screenshot if possible. I'll try to reproduce the SVG problem in firefox 38. 
Did you try to upgrade? I see that latest firefox version is 45.

**Comment by Xaviju** [comment] 2016-04-29 05:46
Can't reproduce. Closing it for now.

**Comment by drzraf** [comment] 2016-04-29 13:34
I just tried with a brand new iceweasel 38.7.1 profile and these 4 SVG still does not appear.
Am I alone using Debian Jessie's Iceweasel?
The fact that some SVG only are affected are a hint about the issue not being from my configuration/customization.
(May I advise you to reopen?)

**Comment by drzraf** [comment] 2016-06-10 04:16
Updated from Iceweasel 38 to Firefox 45 (cf Debian Jessie recent upgrade) and the missing icons appeared to me for the first time.

**Comment by Xaviju** [comment] 2016-06-10 06:09
Great! We did not receive any other feedback about this and it was working for us on firefox so I am not sure what was exactly happening there.
I'm glad it works now.

Thanks

**Closed by Xaviju** 2016-06-10 06:09 UTC
Labels: need validation
