### ISSUE TITLE
Feature Request: team organizations

### ISSUE THREAD

**Issue by kabaka** [taigaio/taiga-front#653] opened 2015-09-28 15:29 UTC
It would be greatly useful to group users into a "team" or "organization" which itself can contain many projects. I suspect such a feature is planned to facilitate the business accounts.

This would be extremely helpful both for the hosted and downloaded versions of Taiga.

Would like to see just a few simple features, such as team logo, grouped projects, and use of the team name in the project URL/slug instead of username.

**Comment by kabaka** [comment] 2015-09-28 18:57
Looks like there is already a US for this. Sorry – must have missed this when I looked earlier! Doesn't mention slugs/URLs, though.

https://tree.taiga.io/project/taiga/us/2129

**Comment by ryanleesipes** [comment] 2015-09-28 19:37
Very interested in this as well.

**Comment by superalex** [comment] 2015-09-29 06:40
Thank you very much @kabaka , I've just added your comment to https://tree.taiga.io/project/taiga/us/2129 so I'm closing this one and leaving the Taiga userstory open.

Regards!,

**Closed by superalex** 2015-09-29 06:40 UTC

**Comment by herbsmn** [comment] 2016-07-04 07:32
I can't seem to click "watch" on the US in taiga. It says "something is wrong". I do want to voice my support for this feature tho too. A work around for now is to create users that are named after the group you want and then create the project with that so that name is in the URL.

**Comment by superalex** [comment] 2016-07-05 05:35
Hello @herbsmn could you please detail the steps to reproduce the watching issue?.

Regards,

**Comment by herbsmn** [comment] 2016-07-05 06:15
I actually can't do much of anything at tree.taiga.io
I can't create a new project. I can't like taiga's project. I can't watch projects.
My user name is @Kwerdts and I use Tails and the Tor Browser Bundle.
I have taiga set up on my own server and I can do all of those things with the hosted version. Are you guys blocking Tor exit nodes IPs in some way?

**Comment by herbsmn** [comment] 2016-07-05 06:16
I am able to navigate around the pages tho.

**Comment by herbsmn** [comment] 2016-07-05 06:17
i'm able to log out but when I try to do much of anything else a red thing comes up at the top of the screen and says OOPS something something.

**Comment by superalex** [comment] 2016-07-05 06:19
We are not blocking any Tor exit nodes (but we are checking it with our IT people). Are you receiving any error in your javascript console?

**Comment by herbsmn** [comment] 2016-07-05 06:23
downloadable font: kern: Too large subtable, table discarded (font-family: "OpenSans-Semibold" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1467052820265/fonts/OpenSans-Semibold.ttf

downloadable font: kern: Too large subtable, table discarded (font-family: "OpenSans-Light" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1467052820265/fonts/OpenSans-Light.ttf

downloadable font: kern: Too large subtable, table discarded (font-family: "OpenSans-Regular" style:normal weight:normal stretch:normal src index:0) source: https://tree.taiga.io/v-1467052820265/fonts/OpenSans-Regular.ttf

**Comment by Xaviju** [comment] 2016-07-05 06:30
This might not be the correct place for this issue since it is not related to " team organizations" and some users might be receiving unwanted emails, could you please open a new issue and reference it here?
Thanks!

**Comment by superalex** [comment] 2016-07-05 06:37
Thanks @Xaviju you are right ;)
