### ISSUE TITLE
Not able to get login page.

### ISSUE THREAD

**Issue by adutta14** [taigaio/taiga-front#1350] opened 2017-08-04 01:47 UTC
Hello,

I have hosted my own taiga. After the configurations, i am not getting the login page. It goes to an infinite loop.

Please check this by hitting this url:- https://taigapro.isdatatower.com

Please advice.

Thanks,
Abhishek Dutta

**Comment by jespino** [comment] 2017-08-04 09:19
Hi Abhishek,

The problem is related with the backend, it's giving 500 errors, normally
this means a problem with the configuration. Can you take a look to the
taiga-back logs and send me the python exceptions that must be there? Or
activate the DEBUG to True in your settings/local.py in taiga back and
restart the taiga-back service in circus.

Regards.

**Comment by Cyr3con** [comment] 2017-08-04 14:36
Hey Jespino,

When i hit the backend url directly on browser, i get a proper 200 response. Also, i didnt see the 500 error code rather it was an infinite loop and the login page would never appear.
Let me know if you still want me to provide you the backend logs here.

Thanks,
Abhishek Dutta

**Comment by jespino** [comment] 2017-08-04 15:17
Yes, to understand what exactly is going on I need to see the logs, if you prefer (to keep privacy) you can send it to support@taiga.io.

**Comment by Cyr3con** [comment] 2017-08-04 21:39
Well, sure.. One strange thing that i noticed is i am able to get the login page in incognito and i was successfully able to login there.

But when i try to login into another browser, i dnt land up in the login page. Do you still want me to share the logs? i checked and i dnt see any other error apart from the DB error which i fixed it.

**Comment by adutta14** [comment] 2017-08-04 21:54
Can you please try to check from your browser if you are getting the login page or not.

Thanks!!

**Comment by adutta14** [comment] 2017-08-04 22:40
That was  a cache problem i believe. Its working fine now.

Thanks.

**Comment by jespino** [comment] 2017-10-30 08:25
Great! I close the issue.

**Closed by jespino** 2017-10-30 08:25 UTC
