### ISSUE TITLE
Drag US back from Sprint to Backlog crash

### ISSUE THREAD

**Issue by erparom** [taigaio/taiga-front#1113] opened 2016-10-03 18:29 UTC
1-Create US (via Epic)
2-Drag US to a Sprint
3-Drag back US from Sprint to Backlog and crashes.

Notes: It does the operation, but "appears to fail" the callback to backlog.

**Comment by superalex** [comment] 2016-10-04 05:27
Hello @erparom does your project contain a lot of userstories in the backlog?

**Comment by talbotseb** [comment] 2016-10-04 09:20
Hi @superalex I have the same problem and yes I have a lot of US in my backlog.
When I scroll and want to see all of the US, the backlog needs to refresh to load all of the US.

**Comment by superalex** [comment] 2016-10-04 18:06
Hello @talbotseb and @erparom we were having some problems related to the infrastructure of the platform (more specifically related with the request headers size). It should be fixed now, could you confirm if the problem is solved?. Sorry for the inconvenience.

Regards,

**Comment by talbotseb** [comment] 2016-10-05 07:11
Hi @superalex : I do confirm it has been solved as I cannot reproduce it since yesterday late afternoon.
Thank you for your great work !

**Comment by superalex** [comment] 2016-10-05 07:18
Great!, you are welcome @talbotseb

**Closed by superalex** 2016-10-05 07:18 UTC
