### ISSUE TITLE
[BUG] Unable to signup

### ISSUE THREAD

**Issue by jonathan-s** [taigaio/taiga-front#65] opened 2021-06-29 17:06 UTC
**Describe the bug**
Not sure if this belongs exactly here, but seems like the best place. 

When signing up using firefox I got an error. It looks like I still got an email, so the signup process isn't entirely broken. 

<img width="785" alt="Screenshot 2021-06-29 at 19 01 53" src="https://user-images.githubusercontent.com/2124818/123839067-006edd80-d90d-11eb-847f-5127ca086b63.png">

**How can we reproduce the behavior**
Signup using firefox. 

**Workarounds**

**Screenshots**

**Taiga environment**

**Desktop (please complete the following information):**
 - **OS:** 
 - **Browser:** 
 - **Version:** 

**Additional context**

**Comment by Xaviju** [comment] 2021-06-30 10:14
Hi @jonathan-s  thanks for reporting. We are trying to reproduce this error on Firefox.
 
I can see the console error as well, but it doesn't prevent the user from signing up. In the description you say that you  `still got an email` so it seems that you signed up but since the title is `Unable to signup` we are concerned about this issue.

Could you please describe the exact issue to understand better? 
Were you finally able to sign up?
Could you provide some step-by-step explanation on how to reproduce the error?

Thanks a lot.

**Comment by jonathan-s** [comment] 2021-06-30 19:07
Hi,

Apologies for being vague. I was able to signup however I was under the
impression that the signup was broken and when the signup form is half
broken it doesn't leave a stellar impression.

(though application besides that seems good)

**Comment by Xaviju** [comment] 2021-07-01 04:52
Thanks @jonathan-s 
When you say is half broken, you mean the console error, or did you find any other errors during the signup process?
We are already checking this console error, but the issue would much more critical is something is not allowing users to sign up using the UI.

Thanks again

**Comment by jonathan-s** [comment] 2021-07-01 06:37
The error `Error executing validation flow` was reflected on the frontend. At that point I thought that the signup form was completely broken. I checked my email, I was still signed up. So at that point I realized that it was only half-broken.

**Comment by Xaviju** [comment] 2021-07-01 08:09
Thanks for the fast response @jonathan-s 
I think we have enough information to reproduce this issue.

**Comment by Xaviju** [comment] 2021-07-05 05:21
We are closing this issue because cannot reproduce the error and sign up seems to be working correctly. 
We cannot see any error on the frontend, but we'll keep an eye on it.
Please reopen if you feel this is not correct and add any screenshots or any relevant information.

Thanks

**Closed as completed by Xaviju** 2021-07-05 05:21 UTC
Labels: bug
