### ISSUE TITLE
"undefined" saved as token in local storage

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-front#627] opened 2015-08-25 02:29 UTC
Somehow, the string value "undefined" was saved as the local storage value for token. This was causing problems because `StorageService.get()` tries to parse it as JSON.

**Comment by superalex** [comment] 2015-08-25 06:22
Hello @brettp,

Have you got more info about how could you achieve this?, I can't reproduce it...

Regards!,

**Comment by brettp** [comment] 2015-08-25 13:40
I think there's more going on. I just did a fresh clone of front master, and after `bower install` I get an empty screen. It doesn't seem to be a caching issue:

<img width="1333" alt="screen shot 2015-08-25 at 9 37 36 am" src="https://cloud.githubusercontent.com/assets/43375/9467951/024d0c4c-4b0d-11e5-9cef-c1ab8ebe523f.png">

**Comment by superalex** [comment] 2015-08-26 08:31
Did you execute the rest of the commands?

sudo npm install -g gulp
sudo npm install -g bower
npm install
bower install
gulp

Could you execute them again and check if there is any error?

**Comment by brettp** [comment] 2015-08-26 15:18
Yes, I had completed the entire installation. Just now I tried doing
another bower update and rebuilt, and things seem to be working. I'll try a
few more ideas on how I think the "undefined" string ended up saved and
close if I can't duplicate.

**Comment by brettp** [comment] 2015-08-27 01:53
Tried reproducing and couldn't, so closing.

**Comment by brettp** [comment] 2015-08-27 04:53
I was able to reproduce the empty screen, though. I set `debugInfo` to true in `conf.json`. That apparently broke the frontend.

**Comment by superalex** [comment] 2015-08-27 05:16
Thanks @brettp we'll review it!

**Comment by juanfran** [comment] 2015-08-31 08:26
Thanks @brettp 

It's been fixed on master branch. It will be in the next release.

**Closed by juanfran** 2015-08-31 08:26 UTC
