### ISSUE TITLE
No users to assign tasks to

### ISSUE THREAD

**Issue by teaguecl** [taigaio/taiga-front#1075] opened 2016-07-15 00:55 UTC
I am running the docker image linked from your install page:  https://github.com/ipedrazas/taiga-docker/

I created a new project, and added several new users to it.  When I click on the "Team" tab on the left of the interface, none of the users are listed.  When I click on a user story or task and click "Assign" I get the "Select assigned to" dialog, with an X at the top right - but no users listed, and no "submit" or "ok"  button.

I then accessed the django admin page at http://localhost/admin and when to the 'tasks' area.  From there I could assign tasks to my users.  However, going back to the Taiga page those tasks still show up as "Unassigned".

It seems like the "empty team page" issue and the "cannot assign task to user" issue are probably related.  It is not possible for me to provide access to my instance - it is on a non-networked machine.  Are there any logs I can look at that would be helpful?

**Comment by superalex** [comment] 2016-07-18 06:22
Hello @teaguecl 

Could you check your javascript console to check if there is a javascript error or the API call for the memberships isn't working properly?

**Comment by teaguecl** [comment] 2016-07-18 22:01
There are no errors in the API console.  However, I have a theory on what's happening.  I was unable to add new users through the normal interface, as I don't have email integration working.  I therefore created users by going to the "http://localhost/admin" page, adding a user, and then going to the normal Taiga interface and setting a valid email address. 
I believe this method of adding users is not sufficient.  In looking at re-adding users the correct way, I'm a bit stuck.  The server is in fact running postfix on port 25 - which is why Taiga thinks everything is OK when I create a new user.  However, postfix must not be configured properly which results in emails not being delivered.  Without the emails, there is no way to actually complete the new user registration.

So I believe my problem has morphed into: Is there a way to add a user without email integration?  Is there any way to retrieve the activation link (content of the email sent) from the logs?

**Comment by teaguecl** [comment] 2016-07-19 00:58
I was able to acquire the invitation email.  I modified invitations.py to print the email to a file, and was able to retrieve the activation URL from there.   I then logged on using the new user, which was created properly.  However, the new user still does not show up in the Team Members section and still cannot have tasks or issues assigned.  So I guess I was wrong about the account creation procedure being the issue - I'm at a loss as to what would cause this, though it looks like I'm not the only one:
https://github.com/ipedrazas/taiga-docker/issues/35

**Comment by superalex** [comment] 2016-07-19 06:28
Could you please attach a screenshot from the memberships area of your project? (select the members menu from your project admin area)

**Comment by teaguecl** [comment] 2016-07-19 17:18
I've placed the screenshot you requested, along with a few others here:
https://www.dropbox.com/sh/a89xx1hxnqe9ibk/AABFu8k6fIO2bdnAd0ckFMnla?dl=0

**Comment by bameda** [comment] 2016-07-19 18:08
You have create the user in Taiga with the superadmin panel, but you have to add them to the project as members too. 

Go to the memberships section in the superadmin panel and create one memberhsip object to associate one user with its role and its project.

Nonetheless Taiga will not work properly without the service emails. You can configure Taiga to print emails in the log change the email backend but I don't know where is the file in the docker image.

**Comment by bameda** [comment] 2016-07-19 18:09
I close this issue because is not a bug in the software, is a problem with the setup with a docker image.

**Closed by bameda** 2016-07-19 18:09 UTC

**Comment by teaguecl** [comment] 2016-07-19 18:32
bameda: All the users have been added to the project via the superadmin tool - they show up properly in the Members tab, but they still do not show up in the Team tab nor can anything be assigned to them.  I also have been getting the service emails via the log and adding users via that mechanism - it fails in the same way.
I agree that this issue is probably related to the docker image - as noted previously several users of that docker have complained of the same problem.

**Comment by bameda** [comment] 2016-07-19 18:50
You can seethe browser console to see if there is some error too when you tray to asign users

**Comment by bameda** [comment] 2016-07-19 18:53
If you can see members in the Team section too in a project is a problem with the image. Apparently all your data is correct.
