### ISSUE TITLE
Issues page - Search is not working

### ISSUE THREAD

**Issue by mangeshlad1986** [taigaio/taiga-front#357] opened 2015-02-20 05:41 UTC
When there are multiple pages in Issues, Search is not working.. In console it is showing not found
![screenshot from 2015-02-20 11 10 24](https://cloud.githubusercontent.com/assets/10572520/6281922/23059c50-b8f1-11e4-859c-e602cc1d214b.png)

**Comment by superalex** [comment] 2015-02-20 06:33
I think the problem is the following:
- list issues
- go to a certain page
- write something in the searchbox

The results aren't updating, could you confirm it's working that way please?

**Comment by mangeshlad1986** [comment] 2015-02-23 14:31
Here are steps - 
1. Go to issue listing
2. There should be pagination to reproduce this issue.
3. Go to 2nd or any page other than 1st one.
4. try to search anything on other page. Search doesn't work and get error Bad request in console.

**Comment by juanfran** [comment] 2015-03-04 12:55
thanks @mangeshlad1986

the problem was fixed in our master branch, it will be in production in the next release

**Closed by juanfran** 2015-03-04 12:55 UTC
Labels: bug
