### ISSUE TITLE
Dialogs should remember unsubmitted values

### ISSUE THREAD

**Issue by leftclickben** [taigaio/taiga-front#320] opened 2015-02-04 10:41 UTC
If I open a dialog, enter some values into the form, then close the dialog and open it again, I would like to see the partially-complete input remain in the form, from before I closed the dialog.

For example, if I click "New User Story", then type in the name of the user story but don't click "Create", I should be able to close the dialog, then reopen it and still see the name, rather than having to retype it.

This behaviour is present in YouTrack.

**Comment by superalex** [comment] 2015-02-04 11:12
It was working in that way but we received feedback from our users saying it was confusing and that it shouldn't remember the status when closing. Their arguments convinced us and we changed it, we could think about it again if it's working properly for most of the users :)

**Comment by leftclickben** [comment] 2015-02-04 11:17
Could it be configurable?  Familiarity with YouTrack has led me to rely somewhat on this.

Maybe also add a "reset" button that clears the values, for those times when you do want to forget the half-finished one?

**Comment by Xaviju** [comment] 2015-02-04 11:26
@leftclickben we made closing a lightbox to be a very conscious action to ensure that you are doing it on purpose and not by mistake. Reset form buttons are long time forgotten in modern web apps. 
I will add your suggestion to our review box but currently is the first feedback against this decision we made long time ago.

**Comment by leftclickben** [comment] 2015-02-04 12:56
@Xaviju I understand that you've made a UX decision and this goes against that, but there are certainly reasons I (and other users, surely) would want to interrupt creation of a user story, then come back to it.  Maybe I'm referencing another user story but I can't remember the number.   Maybe I'm checking a format or convention that I've used previously.  Maybe something urgent has just come up.  

Either way I don't want one keypress or mouse click to destroy the description I just spent 15 minutes writing.  Especially as there is no confirmation of this data loss.

I don't consider closing the lightbox as destroying it, merely hiding it, and I think that is where the difference in UX is.

Regarding the reset button, I wasn't necessarily thinking of a `type="reset"` button, which probably won't work everywhere anyway (with javascript widgets, etc).  I was thinking more of a button that would programmatically clear the form.

**Comment by Xaviju** [comment] 2015-02-04 13:37
@leftclickben sure, I understand the reasons and I think you are right about the problems that you are trying to fix hiding the lightbox instead of resetting it. 
This is my opinion but I think we should be able to find a better way to fix it instead of adding a reset button (sounds really vintage to me) that doesn't contradicts what users usually do in most of the web apps. Closing a lightbox usually means resetting it out there. It's the expected behavior and users asked us to fix when it wasn't that way.

I have a couple ideas that could be useful for everybody:
- Add a warning before closing a lightbox if it already has information.
- US autocomplete when user starts typing #{number}

It probably doesn't fix all the problems but seems be the best of both worlds to me.

**Comment by leftclickben** [comment] 2015-02-04 14:33
Thanks @Xaviju 

The reset button was just an afterthought, not fully thought out.  You are right that they are unpopular but I think they still have their place.  Even in desktop applications something analagous is sometimes used.  Anyway I'm not really that convinced about it being right for this situation myself, like I said it was just something I threw in there.

In terms of closing a lightbox meaning resetting / destroying it...  I think it depends on context, I don't think it's right to say it is usually the case.  Certainly in the case of YouTrack, it means hiding it.

But I think that adding a warning if the form is dirty addresses the real underlying issue, which is that you are destroying data without confirmation.  I'd almost say this should be marked as a bug not an enhancement on that basis :-)

There could also be a "don't warn me about this again" option for people who don't want to be nagged.

The autocomplete is probably a separate issue to this one, but if the autocomplete showed the subject of the US as well, then that would certainly help with creating relationships.

**Comment by Xaviju** [comment] 2015-02-04 14:41
Nice! I will add your comments to the the issue to review it with the team. 

Thank you for your feedback :+1:

**Comment by leftclickben** [comment] 2015-02-04 14:59
No worries.  I see the autocomplete is already listed as #278 and is in progress :-)

**Comment by leftclickben** [comment] 2015-02-05 03:56
I just noticed, in github if you click "New Issue", type something, then go to another page, when you go back and click "New Issue" a second time, the previously unsaved values are still there.  Same even goes for comments.  I just thought I'd mention it because it's a precedent with more weight to it than, say, YouTrack :-)

BTW, meant to also say that I am very impressed by the responsiveness of the team to these issues :-)

**Closed** 2020-12-03 19:17 UTC
Labels: enhancement, taiga-6-clean-up
