### ISSUE TITLE
[Wiki] Text formatting is lost when copy paste

### ISSUE THREAD

**Issue by iwkse** [taigaio/taiga-front#1431] opened 2018-03-24 22:59 UTC
In the Wiki module, if HTML mode is set, copy & paste some text doesn't maintain formatting.
I works fine in Markdown mode.

**Comment by foliovision** [comment] 2019-09-21 13:16
This is a near duplicate of [1280](https://github.com/taigaio/taiga-front/issues/1280).

Quick switch between HTML/Markdown solves the issue. Should be easy to at least keep line breaks though and not strip linebreaks from the incoming text, creating mush.

**Closed** 2020-12-03 10:39 UTC
Labels: taiga-6-clean-up
