### ISSUE TITLE
Need a better editor

### ISSUE THREAD

**Issue by NemoAlex** [taigaio/taiga-front#539] opened 2015-06-19 05:31 UTC
First, thank you all to made such a amazing tool.

But there are some issues for me:
It occupied too many system hotkeys, such as 'Ctrl + P' and 'Ctrl + B'. They are useful hot keys in OS X.
And I feel awful when I write a long article, really need a auto-height feature.

Some other features could be good for users: drag-n-drop image files, link attachments in issue description or comment.

Could you please consider to switch to a better third party editor in this project? Thank you all again.

**Comment by Xaviju** [comment] 2015-06-19 05:47
Hi @NemoAlex it is already in our roadmap to improve the editor, we will take into consideration the features you mentioned.

I will try to keep you informed of this feature status :)

**Comment by brettp** [comment] 2015-09-04 03:48
@Xaviju - Do you have any specific plans about improving the editor? It's also a point of frustration for my team, so I'd like to help if you can share any plans.

**Comment by Xaviju** [comment] 2015-09-04 06:00
We did not have yet a meeting to define the features and how exactly we want to improve the editor, but it is definitively a point of frustration for the team. I can share with you the user story in Taiga, it contains our ideas for editor along with some users comments.
https://tree.taiga.io/project/taiga/us/2114?kanban-status=27

Let's see what @superalex suggests about this :)

**Comment by superalex** [comment] 2015-09-04 06:03
I really like the idea of having https://github.com/ether/etherpad-lite in Taiga but it seems like it would be a huge refactor! :D

**Comment by brettp** [comment] 2015-09-04 22:22
I was actually going to suggest cutting down on the features of the editor. Markdown is so wonderfully simple that it can be written without automated assistance. Admittedly we don't make heavy use of the Wiki, but I think Etherpad Lite would be feature overload. We've integrated together.js for collaboration when we need it, but rarely use it.

The biggest complaints we have about the editor are almost all related to the assistance features:
* Clicking the list buttons doesn't work as expected if you've selected text.
* Making links and inserting images is confusing because of the consecutive popups.
* Unexpected behavior when clicking formatting options without selecting text. The "Your text here..." prompts seem strange.

Whichever direction you want to go, I'm happy to help with what I can.

**Comment by superalex** [comment] 2015-09-08 09:23
Thank you very very much @brettp. We had been consulting a lot of our users and they are missing something more powerful than Markdown, and you are completely right, the actual editor is not very good...Some of our projects have a big load of wiki editions so the collaboration feature would be a great extra :)

**Comment by pmirandaarias** [comment] 2018-05-17 16:13
So? almost 3 years and the text editor in issues it still plane

**Comment by diacritica** [comment] 2019-10-09 12:15
fixed in earlier releases

**Closed by diacritica** 2019-10-09 12:15 UTC
Labels: enhancement
