### ISSUE TITLE
UI - user stories status not aligned

### ISSUE THREAD

**Issue by jerem-ie** [taigaio/taiga-front#1106] opened 2016-10-01 15:48 UTC
The user stories status ( admin/project-values/status )  aren't properly left aligned. The other one are ok. Visible in the latest taiga-front-dist (3.0)

![liste decallee](https://cloud.githubusercontent.com/assets/6639669/19015128/6164bad4-87fe-11e6-994a-cf5c1d888669.png)

**Comment by bameda** [comment] 2016-10-01 17:45
I can't reproduce it, what browser and what version are you using? Can you test it with another one?

**Comment by jerem-ie** [comment] 2016-10-02 09:04
hi, 

i just try in another computer. It's apprently a screen size issue. Try to shrink your browser window and will collapse around 1300-1400 px wide.

In a UX point of view, it's certainly more practical to shrink or collapse the secondary sidebar when the tertiary sidebar is open.

**Comment by Xaviju** [comment] 2016-10-02 09:06
Validated. Thanks for reporting, we'll fix it ASAP

**Comment by Xaviju** [comment] 2016-10-03 09:57
This is fixed in https://github.com/taigaio/taiga-front/commit/d3265dcb34bf90c4c6480f599780063992a07adc

The problem was caused by the amount of information in small screens. The fix hides the slug and WIP columns in small screens. It needs to be validated by the team before updating.

@jerem-ie What do you think?

**Comment by jerem-ie** [comment] 2016-10-03 11:40
it's a good idea @Xaviju 
i don't use the slug, and don't see where it could be usefull ?

**Comment by Xaviju** [comment] 2016-10-03 11:43
@jerem-ie it is useful to link commits and actions in Taiga, but it only informative: https://tree.taiga.io/support/integrations/changing-elements-status-via-commit-message/

**Closed by Xaviju** 2016-10-03 11:43 UTC
Labels: bug
